//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientIM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment_like
    {
        public int comment_id { get; set; }
        public int person_id { get; set; }
        public string timestamp { get; set; }
        public string read { get; set; }
        public int comment_like_id { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
