//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientIM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendLink
    {
        public int requester { get; set; }
        public int requested { get; set; }
        public string status { get; set; }
        public string timestamp { get; set; }
        public string read { get; set; }
        public string approved { get; set; }
        public int friendLink_id { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual Profile Profile1 { get; set; }
    }
}
